default_platform(:ios)

desc 'Set Marketing and Build version'
lane :set_version do |version|
  increment_version_number(
    version_number: version[:version],
    xcodeproj: "./Projects/iOSApp/Application/EarthIsRound.xcodeproj"
  )
  
  increment_build_number(
    build_number: Time.new.strftime("%Y.%m%d.%H%M"), # 2023.0228.1138
    xcodeproj: "./Projects/iOSApp/Application/EarthIsRound.xcodeproj"
  )
end


################## QA

desc 'Upload QA App'
lane :QA do |options|
  set_version(version: options[:version])

  version_number = "#{lane_context[SharedValues::VERSION_NUMBER]}(#{lane_context[SharedValues::BUILD_NUMBER]})"

  commit_version_bump(
    message: "Update version - #{version_number}",
    xcodeproj: "./Projects/iOSApp/Application/EarthIsRound.xcodeproj"
  )
  add_git_tag(tag: "v#{version_number}")
  push_to_git_remote
end

################## Managing xcconfigs

desc 'Set Marketing Version in Xcconfig'
lane :set_version_xcconfigs do |options|
    version_bump(options[:version])
end

def version_bump(target)
    file_path = 'xcconfigs/Base/Projects/Shared.xcconfig'
    version_key = 'MARKETING_VERSION'

    puts "New Version: #{target}"

    update_xcconfig_value(
      path: file_path,
      name: version_key,
      value: target
    )
end

################## Match

# match 인증서 파일 생성 -> 관리자용

platform :ios do
  lane :matchByTeam do
      match(git_branch: "master", type: "appstore")
      match(git_branch: "master", type: "development")
  end
end

# match 인증서 받아오기 -> 팀원용

platform :ios do
  lane :matchReadOnly do
      match(git_branch: "master", type: "appstore", readonly: true)
      match(git_branch: "master", type: "development", readonly: true)
  end
end